### ISSUE TITLE
Wrong title ID for BootMii Launcher

### ISSUE THREAD

**Issue by NezbednikSK** [Gabubu-WADs/wads-website#2]
Copy-paste error?
![image](https://github.com/Gabubu-WADs/wads-website/assets/47603275/a5900aa5-ef76-422a-ada0-40cfb93feeff)

**Comment by GabubuAvailable** [comment]
The issue has been solved. Thank you!
![image](https://github.com/Gabubu-WADs/wads-website/assets/88589756/1a809a14-c702-4c9e-a790-83d07d228624)
